AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CobaltaX Monitor Backend (Audit + Users) - Phase 1

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 256
    Tracing: Active

Parameters:
  TenantId:
    Type: String
    Default: default
  StageName:
    Type: String
    Default: dev

Resources:
  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: audit_events
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenant_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: tenant_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowMethods: "GET,POST,OPTIONS"
        AllowHeaders: "*"
        AllowOrigin: "*"

  AuditBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audit-batch
      CodeUri: lambdas/
      Handler: audit_batch.lambda_handler
      Environment:
        Variables:
          AUDIT_TABLE: !Ref AuditTable
          TENANT_ID: !Ref TenantId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditTable
      Events:
        AuditBatchApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /audit/batch
            Method: post

  UsersGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: users-get
      CodeUri: lambdas/
      Handler: users_get.lambda_handler
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          TENANT_ID: !Ref TenantId
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        UsersGetApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users
            Method: get

Outputs:
  ApiUrl:
    Description: Base URL of the API
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
